server:
  port: 8899

#application name
spring:
  application:
    name: config-server

#configuration Eureka Client
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
